### ISSUE TITLE
Socket hang up error

### ISSUE THREAD

**Issue by mir123** [digidem/mapeo-settings#4]
I'm getting the following error when running `npm run build`:

```
npm run build

> mapeo-default-settings@3.5.0 build /home/<user>/mapeo-settings
> mkdirp build && mapeo-settings build -l 'en' -o build/${npm_package_name}-v${npm_package_version}.mapeosettings

→ Using version 3.3.1 of mapeo-settings-builder
! Warning: no category json files found in /home/<user>/mapeo-settings/categories
✓ Built presets and categories (47ms)
✓ Generated svg sprite for iD (427ms)
✓ Generated png sprite for Mapbox (47ms)
✖ (node:21758) UnhandledPromiseRejectionWarning: Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at Socket.socketOnEnd (_http_client.js:453:23)
    at Socket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
✖ (node:21758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
✖ (node:21758) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

npm version: 6.14.4

**Comment by mir123** [comment]
I realise now I should have filed this in mapeo-settings-builder, but I'll continue here.

After global installation of mapeo-settings-builder, here's the error:

```
$ mapeo-settings build
→ Using version 3.3.1 of mapeo-settings-builder
! Warning: no category json files found in /home/<user>/mapeo-settings/categories
✓ Built presets and categories (55ms)
✓ Generated svg sprite for iD (505ms)
✓ Generated png sprite for Mapbox (59ms)
✖ (node:30256) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! spawn /usr/lib/node_modules/mapeo-settings-builder/node_modules/puppeteer/.local-chromium/linux-536395/chrome-linux/chrome EACCES


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/mapeo-settings-builder/node_modules/puppeteer/lib/Launcher.js:239:14)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/mapeo-settings-builder/node_modules/puppeteer/lib/Launcher.js:230:64)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
✖ (node:30256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
✖ (node:30256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
